### ISSUE TITLE
requirements.txt실행시 오류가 발생합니다. 

### ISSUE THREAD

**Issue by jyes90** [Road-Balance/SpotMicroJetson#3]
Jetson Nano 사용중이며
강의자료에 나와있는 순서대로 작업을 진행했습니다. 

(test_env) spot@spot-desktop:~/SpotMicroJetson/JetsonNano$ pip3 install -U -r requirements.txt
Collecting numpy-stl (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8f/4b/885cfe0754b1692cb47eb1666d7b1beece4c8eeb99cffddc31ccc8725d23/numpy-stl-2.13.0.tar.gz (477kB)
    100% |████████████████████████████████| 481kB 816kB/s
Collecting matplotlib (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/7b/b3/7c48f648bf83f39d4385e0169d1b68218b838e185047f7f613b1cfc57947/matplotlib-3.3.3.tar.gz (37.9MB)
    100% |████████████████████████████████| 37.9MB 13kB/s

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-9y1jf38v/numpy-1.20.0rc1/setup.py", line 30, in <module>
        from setuptools import setup, find_packages, Extension
    RuntimeError: Python version >= 3.7 required.
   
    During handling of the above exception, another exception occurred:
   
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u4n_e7fk/matplotlib/setup.py", line 298, in <module>
        cmdclass=cmdclass,
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/spot/test_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/home/spot/test_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/home/spot/test_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-9y1jf38v/numpy-1.20.0rc1/setup.py", line 30, in <module>
        from setuptools import setup, find_packages, Extension
    RuntimeError: Python version >= 3.7 required.
   
    Edit setup.cfg to change the build options; suppress output with --quiet.
   
    BUILDING MATPLOTLIB
      matplotlib: yes [3.3.3]
          python: yes [3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC 8.4.0]]
        platform: yes [linux]
     sample_data: yes [installing]
           tests: no  [skipping due to configuration]
          macosx: no  [Mac OS-X only]
   
   
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-u4n_e7fk/matplotlib/
위의 오류가 발생합니다.

**Comment by kimsooyoung** [comment]
해당 부분 다음과 같이 수정 완료하였습니다.

혹 아래와 같은 수정 후에도 같은 문제가 반복된다면 알려주세요

감사합니다.

```
matplotlib==2.1.1
numpy==1.13.3
keyboard==0.13.5
getch==1.0
adafruit-circuitpython-servokit==1.3.0
Adafruit-PCA9685==1.0.1
Adafruit-SSD1306==1.6.2
adafruit-circuitpython-pca9685==3.3.2
smbus
psutil
```

**Comment by jyes90** [comment]
(test_env) spot@spot-desktop:~/SpotMicroJetson/JetsonNano$ pip3 install -U -r requirements.txt
Collecting matplotlib==2.1.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/50/27/57ab73d1b094540dec1a01d2207613248d8106f3c3f40e8d86f02eb8d18b/matplotlib-2.1.1.tar.gz (36.1MB)
    100% |████████████████████████████████| 36.1MB 14kB/s 



    Complete output from command python setup.py egg_info:
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.1]
                    python: yes [3.6.9 (default, Oct  8 2020, 12:12:24)  [GCC
                            8.4.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
                       six: yes [six was not found.pip will attempt to install
                            it after matplotlib.]
                  dateutil: yes [dateutil was not found. It is required for date
                            axis support. pip/easy_install may attempt to
                            install it after matplotlib.]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [pytz was not found. pip/easy_install may
                            attempt to install it after matplotlib.]
                    cycler: yes [cycler was not found. pip/easy_install may
                            attempt to install it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: yes [version 2.8.1]
                       png: yes [version 1.6.34]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
    Traceback (most recent call last):
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-p9wo0iwr/numpy-1.20.0rc1/setup.py", line 30, in <module>
        if os.path.exists('MANIFEST'):
    RuntimeError: Python version >= 3.7 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-75pcqlet/matplotlib/setup.py", line 296, in <module>
        **extra_args
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/spot/test_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "/home/spot/test_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "/home/spot/test_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 724, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 909, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1163, in run_setup
        run_setup(setup_script, args)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/spot/test_env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-p9wo0iwr/numpy-1.20.0rc1/setup.py", line 30, in <module>
        if os.path.exists('MANIFEST'):
    RuntimeError: Python version >= 3.7 required.
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: yes [version 9.26]
                     latex: no
                   pdftops: yes [version 0.62.0]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-75pcqlet/matplotlib/

수정되었다고하셔서, 젯슨나노 OS삭제후 다시 진행하였으나 위의 오류가 발생하였습니다.

**Comment by kimsooyoung** [comment]
강의 자료 중에 다음과 같은 부분 따라하신 것 맞으실까요?

```bash
# 하드웨어 구동에 필요한 리눅스 패키지들 설치
$ sudo apt install python-dev python-pip python3-pip libfreetype6-dev libavdevice-dev libavfilter-dev libswscale-dev libavformat-dev libjpeg-dev build-essential -y
$ sudo apt install libsdl-dev libportmidi-dev libsdl-ttf2.0-dev libsdl-mixer1.2-dev libsdl-image1.2-dev -y 
```

강의를 위해 순정 상태에서 확인 후 업데이트 하였는데, 저도 다시 확인해보겠습니다.

감사합니다.

**Comment by jyes90** [comment]
네. 순정상태에서 14강 아래쪽의 다시 jetson 부분 그대로 따라하였습니다.

**Comment by jyes90** [comment]
문제를 해결했습니다. pip, setuptools 버전의 문제인거같습니다.
sudo apt-get install python3-pip
sudo apt-get install python3-pip
pip install --upgrade setuptools
위 3가지 명령어 진행후에 해결되었습니다.

**Comment by kimsooyoung** [comment]
정말 감사합니다!! 해당 내용 강의자료에도 추가 하였습니다. 

좋은 하루 되세요 😀😀

## 다시 Jetson!!
# contribution from jyes90

![image](https://user-images.githubusercontent.com/12381733/102505034-e08c7080-40c4-11eb-8b4e-8848c9973565.png)

**Comment by jyes90** [comment]
저도 정말 감사드립니다. 
그리고 제가 잘못올린 부분이 있네요. 
sudo apt-get install python3-pip
pip install --upgrade pip
pip install --upgrade setuptools
이렇게 진행했습니다. 

근데 sudo apt-get install python3-pip는 진행 안해도 될거같긴 합니다. 테스트를 다시 진행해보지 않아서 확실하진 않네요. 
아래는 sudo apt-get install python3-pip를 실행했을 때 나온 내용입니다. 
(spot_env) jetson@jetson-desktop:~/SpotMicroJetson/JetsonNano$ sudo apt-get install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.4).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.

기존코드에 보면 python3-pip 설치부분이 있어서 중복되기도 하고요. 그래서 제생각엔 기존 코드 뒤에 
pip install --upgrade pip
pip install --upgrade setuptools
이 두가지가 추가되는게 좋을것 같습니다.

**Comment by kimsooyoung** [comment]
👍 👍  상세한 설명 다시 한 번 감사드립니다. 말씀 주신 바와 같이 강의자료를 업로드 하였으며, `Readme.md` 또한 업데이트 하였습니다. 
 
**jyes90**님 덕분에 다른 사용자분들께서도 해당 부분 어려움 없이 진행 가능하실 것 같습니다. 

🎇 Github 첫 `Contribution`을 축하드립니다. 🎇

![image](https://user-images.githubusercontent.com/12381733/102563824-84096f80-411d-11eb-8a21-b2274a4d787d.png)
